extends SceneTree

const ShipModelScript = preload("res://scripts/ship_model.gd")
const ShipBodyScript = preload("res://scripts/ship_body.gd")
const NeutralPartScript = preload("res://scripts/neutral_part.gd")
const MainScript = preload("res://scripts/main.gd")
const ShipDestructionEffectScript = preload("res://scripts/ship_destruction_effect.gd")
const PhysicsData = preload("res://scripts/physics_tuning.gd")
const BalanceData = preload("res://scripts/balance.gd")
const VisualData = preload("res://scripts/visual_tuning.gd")

var failures: Array[String] = []

func expect(condition: bool, label: String) -> void:
	if condition:
		print("[PASS] ", label)
	else:
		failures.append(label)
		push_error("[FAIL] " + label)

func _init() -> void:
	expect(is_equal_approx(PhysicsData.retain_factor(PhysicsData.PLAYER_LINEAR_RETAIN_PER_SECOND, 1.0), 0.16), "웹 기준 1초 선형 감쇠 계수")
	expect(is_equal_approx(PhysicsData.retain_factor(PhysicsData.PLAYER_ANGULAR_RETAIN_PER_SECOND, 1.0), 0.02), "웹 기준 1초 각 감쇠 계수")
	expect(is_equal_approx(PhysicsData.retain_factor(PhysicsData.PLAYER_LINEAR_RETAIN_PER_SECOND, 0.5), 0.4), "웹 기준 반초 지수 감쇠")
	var ship = ShipModelScript.new()
	ship.initialize_player()
	expect(ship.parts.size() == 15, "웹 초기 함선 15파트")
	expect(ship.core_part().hp == 200.0, "웹 초기 코어 200 HP")
	var thruster_tuning := BalanceData.module_spec("thruster")
	var shield_tuning := BalanceData.module_spec("shield_generator")
	expect(is_equal_approx(float(thruster_tuning.force), 4750.0), "CSV 메인 스러스트 5배 조정")
	expect(is_equal_approx(float(BalanceData.module_spec("rcs_thruster").force), 5400.0), "CSV RCS 스러스트 2배 조정 (5,400)")
	expect(str(thruster_tuning.description) == "주 전진 추진기" and str(thruster_tuning.weapon_type) == "none", "CSV 파트 이름·설명·무기 유형 로드")
	var laser_tuning := BalanceData.module_spec("laser")
	expect(str(laser_tuning.weapon_display_name) == "PULSE LASER" and not str(laser_tuning.weapon_display_desc).is_empty(), "CSV 무기 표시 이름·설명 로드")
	expect(str(BalanceData.module_spec("armor").design_theme) == "terran_human" and str(BalanceData.module_spec("armor").grade_color) == "gray", "테란·인간 일반 등급 파트 분류 로드")
	expect(str(laser_tuning.design_theme) == "protoss_hitec" and str(laser_tuning.themed_name) == "PR-RAR-LASER-ARRAY", "프로토스·하이테크 희귀 파트 네이밍 로드")
	expect(str(BalanceData.module_spec("wedge").design_theme) == "zerg_biological" and str(BalanceData.module_spec("wedge").theme_code) == "ZG", "저그·생물 파트 테마 분류 로드")
	var torpedo_tuning := BalanceData.module_spec("mini_missile_launcher")
	expect(str(torpedo_tuning.display_name) == "AUTO TORPEDO RACK" and str(torpedo_tuning.weapon_display_name) == "AUTO GUIDED TORPEDO", "기본 자동 유도 어뢰 발사기 표시 데이터 로드")
	expect(is_equal_approx(float(BalanceData.WEAPONS.laser.life), 2.25) and is_equal_approx(float(BalanceData.WEAPONS.machine_gun.life), 1.725) and is_equal_approx(float(BalanceData.WEAPONS.railgun.life), 2.475), "레이저·탄도 무기 사정거리 1.5배")
	expect(is_equal_approx(float(BalanceData.WEAPONS.missile.range), 1470.0) and is_equal_approx(float(BalanceData.WEAPONS.mini_missile.range), 2175.0), "미사일 무기 사정거리 1.5배")
	expect(float(shield_tuning.hull) == 22.0 and float(shield_tuning.shield) == 1.0 and float(shield_tuning.power) == -3.0, "CSV Hull·Shield·Power 로드")
	var beam4_tuning := BalanceData.module_spec("beam4")
	var beam3_tuning := BalanceData.module_spec("beam3")
	expect(str(beam4_tuning.material) == "advanced_metal" and float(beam4_tuning.mass) > float(beam3_tuning.mass) and float(beam4_tuning.hull) > float(beam3_tuning.hull), "고급 금속 파트 질량·Hull 상향 튜닝")
	expect(ship.total_mass() > 0.0, "기본 함선 질량")
	expect(ship.shield_capacity() == 1, "기본 방어막 1 레이어")
	expect(is_equal_approx(ship.power_balance(), 1.0), "CSV Power 기반 초기 전력 합계")
	var bounded_ship = ShipBodyScript.new()
	bounded_ship.initialize_player()
	var base_bound_radius: float = bounded_ship.hull_bound_radius
	bounded_ship.model.add("beam4", Vector2i(7, 0))
	bounded_ship.refresh_mass()
	expect(bounded_ship.hull_bound_radius > base_bound_radius, "다칸 확장 뒤 바운드 스피어 확대")
	var collision_box := bounded_ship.collision_box_rect()
	expect(collision_box.size.x > float(PhysicsData.SHIP_COLLIDER_SIZE.x) and collision_box.has_point(Vector2(7 * BalanceData.CELL, 0.0)), "조립체 외곽 AABB 충돌 박스 갱신")
	expect(bounded_ship.contains_world_collision_point(bounded_ship.to_global(collision_box.get_center())), "회전 가능한 충돌 박스 내부 피격 판정")
	expect(not bounded_ship.contains_world_collision_point(bounded_ship.to_global(collision_box.end + Vector2(1.0, 1.0))), "충돌 박스 밖 지점은 구체 근사로 판정하지 않음")
	expect(ResourceLoader.exists(VisualData.VOXEL_PART_TEXTURE_ATLAS, "Texture2D"), "규격 복셀 파트 도트 텍스처 아틀라스 포함")
	var unique_texture_pairs := 0
	for texture_theme in VisualData.PART_TEXTURE_THEMES:
		for texture_grade in VisualData.PART_TEXTURE_GRADES:
			for texture_part in VisualData.PART_TEXTURE_PART_TYPES:
				var texture_spec := {"design_theme": texture_theme, "grade": texture_grade}
				expect(FileAccess.file_exists(VisualData.part_texture_path(texture_part, texture_spec)) and FileAccess.file_exists(VisualData.part_texture_path(texture_part, texture_spec, true)), "종족·등급·타입별 알베도/RGB 마스크 텍스처 쌍: %s/%s/%s" % [texture_theme, texture_grade, texture_part])
				unique_texture_pairs += 1
	expect(unique_texture_pairs == 315 and ResourceLoader.exists("res://shaders/part_masked_material.gdshader", "Shader"), "315개 고유 파트 텍스처와 RGB 마스크 셰이더 등록")
	var other_ship = ShipBodyScript.new()
	other_ship.initialize_player()
	other_ship.global_position = Vector2(bounded_ship.hull_bound_radius + other_ship.hull_bound_radius + 16.0, 0.0)
	expect(bounded_ship.is_within_surface_range(other_ship, 16.1), "바운드 스피어를 포함한 제곱 거리 범위 판정")
	expect(not bounded_ship.is_within_surface_range(other_ship, 15.8), "바운드 스피어 외곽 간격 초과 거부")
	expect(ship.ammo_total("missile") == 6, "미사일 탄약 분리")
	expect(ship.ammo_total("bullet") == 0, "기본 함선은 총알 탄약고 미장착")
	expect(ship.consume_ammo("missile", 2), "미사일 탄약 소비")
	expect(ship.ammo_total("missile") == 4, "미사일 재고 갱신")
	var assembly = ShipModelScript.new()
	assembly.add("core", Vector2i.ZERO)
	assembly.add("armor", Vector2i(1, 0))
	var beam = assembly.make_part("beam3", Vector2i(5, 0))
	expect(not assembly.can_place(beam, Vector2i(5, 0)), "떨어진 파트 장착 거부")
	expect(assembly.can_place(beam, Vector2i(2, 0)), "인접 다칸 파트 장착 허용")
	var bridge = assembly.add("block", Vector2i(2, 0))
	var loose = assembly.add("block", Vector2i(3, 0))
	assembly.remove(bridge.uid)
	var detached := assembly.detach_disconnected()
	expect(detached.any(func(part): return part.uid == loose.uid), "코어 비연결 파트 분리")
	expect(detached.size() == 1, "연결부 제거 뒤 단절 덩어리만 분리")
	var candidate_ship = ShipModelScript.new()
	candidate_ship.add("core", Vector2i.ZERO)
	var candidate_beam := candidate_ship.make_part("beam3", Vector2i(8, 3))
	var beam_candidates := candidate_ship.attachment_candidates(candidate_beam)
	expect(not beam_candidates.is_empty(), "다칸 파트 외곽 장착 후보 생성")
	expect(beam_candidates.all(func(anchor): return candidate_ship.can_place(candidate_beam, anchor)), "장착 후보는 실제 clearance 통과")
	var a := ship.make_part("ammo_bay", Vector2i.ZERO)
	var b := ship.make_part("ammo_bay", Vector2i.ZERO)
	var merged := ship.merge_bays(a, b)
	expect(merged != null and merged.ammo == 12 and merged.capacity == 12, "같은 탄약고 병합")
	expect(ship.merge_bays(a, ship.make_part("bullet_bay", Vector2i.ZERO)) == null, "다른 탄약고 병합 거부")
	var armed_ship = ShipBodyScript.new()
	armed_ship.model.initialize_player()
	var laser_shots := armed_ship.fire_primary_weapons(Vector2(600, 0))
	expect(laser_shots.size() == 2, "웹 기본 2개 레이저 동시 발사")
	expect(is_equal_approx(armed_ship.heat, 17.0), "레이저 발열 11 + 레이저당 3")
	var missile_before: int = armed_ship.model.ammo_total("missile")
	var minis := armed_ship.fire_auto_mini_missiles(Vector2(600, 0))
	expect(minis.size() == 2 and armed_ship.model.ammo_total("missile") == missile_before - 2, "기본 좌우 자동 유도 어뢰가 분리 탄약을 소비")
	var wedge := ship.make_part("wedge_long", Vector2i.ZERO, 1)
	expect(wedge.cells().has(Vector2i(0, 1)), "긴 웨지 회전 점유 격자")
	var wreckage_model := ShipModelScript.new()
	var scrap_candidate := wreckage_model.make_part("armor", Vector2i.ZERO)
	var survivor_candidate := wreckage_model.make_part("armor", Vector2i.ZERO)
	var destruction_main := MainScript.new()
	var scrap := destruction_main.destroyed_wreckage_from_part(scrap_candidate)
	var survivor := destruction_main.destroyed_wreckage_from_part(survivor_candidate)
	expect(scrap.kind == "scrap" and is_equal_approx(scrap.hp, 1.0), "격침 잔해 다수는 회수 전용 스크랩으로 전환")
	expect(survivor.kind == "armor" and survivor.hp < survivor.max_hp, "생존 장착 파트는 격침 피해를 유지")
	var debris := NeutralPartScript.new()
	debris.setup(survivor, Vector2(80.0, 0.0), 4.0)
	expect(float(PhysicsData.DEBRIS_INERTIA_MULTIPLIER) >= 6.0 and debris.part_inertia_radius_squared() > 0.0, "2D 잔해 회전 관성 모멘트 상향 적용")
	expect(float(PhysicsData.DEBRIS_MAX_ANGULAR_SPEED) <= 0.72, "잔해 각속도 상한으로 급회전 방지")
	var destruction_effect := ShipDestructionEffectScript.new()
	var released_uids: Array[int] = []
	destruction_effect.fragment_requested.connect(func(part_uid: int): released_uids.append(part_uid))
	destruction_effect.setup([Vector2.ZERO, Vector2(30.0, 0.0)], [41, 42])
	destruction_effect.spawn_burst()
	destruction_effect.spawn_burst()
	expect(released_uids == [41, 42], "연쇄 폭발마다 부품 하나씩 순차 분리")
	expect(float(VisualData.SHIP_DESTRUCTION_BURST_DURATION) >= 3.0 and float(VisualData.SHIP_DESTRUCTION_BURST_INTERVAL) >= 0.2, "수 초간 간헐적인 격침 폭발 연출")
	var collapsing_ship := ShipBodyScript.new()
	collapsing_ship.initialize_player()
	collapsing_ship.shield_layers = 0
	var collapsing_core := collapsing_ship.model.core_part()
	var core_detached := collapsing_ship.damage_part(collapsing_core, collapsing_core.hp + 1.0)
	expect(core_detached.is_empty() and collapsing_ship.model.core_part() != null and collapsing_ship.model.core_part().hp <= 0.0, "코어 파괴 시 선체를 즉시 비우지 않고 붕괴 상태 유지")
	collapsing_ship.begin_destruction()
	expect(collapsing_ship.is_destroying, "붕괴 중에는 추진 입력을 잠그는 선체 상태 적용")
	expect(collapsing_ship.collision_layer == 0 and collapsing_ship.collision_mask == 0, "붕괴 원본 선체를 물리 고스트로 전환")
	destruction_effect.free()
	destruction_main.free()
	debris.free()
	collapsing_ship.free()
	armed_ship.free()
	bounded_ship.free()
	other_ship.free()
	if failures.is_empty():
		print("[PASS] godot-runtime")
		quit(0)
	else:
		print("[FAIL] godot-runtime: ", ", ".join(failures))
		quit(1)
